{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "93a4c8eb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "---------\n",
      "-       -\n",
      "- o   o -\n",
      "-       -\n",
      "---------\n",
      "Press Y to roll againy\n",
      "---------\n",
      "-       -\n",
      "-   o   -\n",
      "-       -\n",
      "---------\n",
      "Press Y to roll againy\n",
      "---------\n",
      "- o   o -\n",
      "-   o   -\n",
      "- o   o -\n",
      "---------\n",
      "Press Y to roll againy\n",
      "---------\n",
      "-       -\n",
      "-   o   -\n",
      "-       -\n",
      "---------\n",
      "Press Y to roll againy\n",
      "---------\n",
      "- o     -\n",
      "-   o   -\n",
      "-     o -\n",
      "---------\n",
      "Press Y to roll againy\n",
      "---------\n",
      "- o   o -\n",
      "-       -\n",
      "- o   o -\n",
      "---------\n",
      "Press Y to roll againy\n",
      "---------\n",
      "- o   o -\n",
      "- o   o -\n",
      "- o   o -\n",
      "---------\n",
      "Press Y to roll againy\n",
      "---------\n",
      "-       -\n",
      "-   o   -\n",
      "-       -\n",
      "---------\n"
     ]
    }
   ],
   "source": [
    "import random\n",
    "x=random.randint(1,6)\n",
    "\n",
    "m='y'\n",
    "while m=='y':\n",
    "    x=random.randint(1,6)\n",
    "    if x==1:\n",
    "        print(\"---------\")\n",
    "        print(\"-       -\")\n",
    "        print(\"-   o   -\")\n",
    "        print(\"-       -\")\n",
    "        print(\"---------\")\n",
    "    if x==2:\n",
    "        print(\"---------\")\n",
    "        print(\"-       -\")\n",
    "        print(\"- o   o -\")\n",
    "        print(\"-       -\")\n",
    "        print(\"---------\")\n",
    "    if x==3:\n",
    "        print(\"---------\")\n",
    "        print(\"- o     -\")\n",
    "        print(\"-   o   -\")\n",
    "        print(\"-     o -\")\n",
    "        print(\"---------\")\n",
    "    if x==4:\n",
    "        print(\"---------\")\n",
    "        print(\"- o   o -\")\n",
    "        print(\"-       -\")\n",
    "        print(\"- o   o -\")\n",
    "        print(\"---------\")\n",
    "    if x==5:\n",
    "        print(\"---------\")\n",
    "        print(\"- o   o -\")\n",
    "        print(\"-   o   -\")\n",
    "        print(\"- o   o -\")\n",
    "        print(\"---------\")\n",
    "    if x==6:\n",
    "        print(\"---------\")\n",
    "        print(\"- o   o -\")\n",
    "        print(\"- o   o -\")\n",
    "        print(\"- o   o -\")\n",
    "        print(\"---------\")\n",
    "    m=input(\"Press Y to roll again\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "442c9864",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "96ab6106",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
